services:

### registry ###########################################
  registry:
    container_name: ${DOCKER_NAME}-registry
    image: registry
    restart: "unless-stopped"
    volumes:
      - ${DATA_PATH}/registry:/var/lib/registry
    ports:
      - "${REGISTRY_PORT:-5000}:5000"
